robotAvatar/avatar/sound_capture:
  ros__parameters:
    audio_port: 3
    topic: /robotAvatar/avatar/in_raw_audio
    non_speaking_duration: 1.0
    pause_threshold: 1.0
    debug: False
robotAvatar/avatar/sound_to_text:
  ros__parameters:
    topic: /robotAvatar/avatar/in_raw_audio
    device: cpu
    message: /robotAvatar/avatar/in_message
    model: base
    listen: /robotAvatar/avatar/listen
    not_listen_timeout: 2.0
    debug: False
robotAvatar/avatar/text_to_sound:
  ros__parameters:
    debug: False
    audio: /robotAvatar/avatar/out_raw_audio
    message: /robotAvatar/avatar/out_message
    voice_model: /home/vgrlab/Documents/avatar/Avatar2/tts_models/en_US-lessac-high.onnx
robotAvatar/avatar/text_to_wav:
  ros__parameters:
    debug: False
    audio_dir: /tmp/avatar
    audio_raw: /robotAvatar/avatar/out_raw_audio
    message: /robotAvatar/avatar/out_message
    voice_model: /home/vgrlab/Documents/avatar/Avatar2/tts_models/en_US-lessac-high.onnx
robotAvatar/avatar/sentiment_analysis:
  ros__parameters:
    debug: True
    topic: /robotAvatar/avatar/in_raw_audio
    sentiment: /robotAvatar/avatar/sentiment_analysis
    sentiments: ["anger", "excited", "neutral", "sad", "happy", "fear", "surprised"]
    classification_model: /home/vgrlab/Documents/avatar/Avatar2/src/avatar2/classification_model/model
robotAvatar/avatar/avatar_camera:
  ros__parameters:
    debug: False
    port: 0
    topic: /robotAvatar/avatar/avatar_camera/image_raw
robotAvatar/avatar/avatar_camera_view:
  ros__parameters:
    debug: False
    image: /robotAvatar/avatar/avatar_camera/image_raw
robotAvatar/avatar/head_detect:
  ros__parameters:
    camera_topic: /robotAvatar/avatar/avatar_camera/image_raw
    face_topic: /robotAvatar/avatar/faces
    known_faces: /home/vgrlab/Documents/Hacking/Avatar2/scenarios/owl/faces
    debug: False
robotAvatar/avatar/view_head_info:
  ros__parameters:
    face: /robotAvatar/avatar/faces
    debug: True
robotAvatar/avatar/user_monitor:
  ros__parameters:
    tracker_topic: /robotAvatar/avatar/users
    debug: True
robotAvatar/avatar/user_tracker:
  ros__parameters:
    face_topic: /robotAvatar/avatar/faces
    tracker_topic: /robotAvatar/avatar/users
    conversation_timeout: 5.0
    new_person_threshold: 1.0
    intimate: 0.11
    personal: 0.05
    social: 0.02
    debug: False
    
