welcomeAvatar/avatar/ava_bridge:
  ros__parameters:
    port: 5678
    ipaddr: "127.0.0.1"
    debug: True
    avatar_names : [ "welcomeAvatar" ]
    in_message: /avatar/in_message
    out_message: /avatar/out_message
    out_command: /avatar/out_command
