welcomeAvatar/avatar/ava_bridge:
  ros__parameters:
    port: 5678
    ipaddr: "127.0.0.1"
    debug: True
    in_message: /welcomeAvatar/avatar/in_message
    out_message: /welcomeAvatar/avatar/out_message
    avatar_name: welcomeAvatar
    out_command: /welcomeAvatar/avatar/out_command